import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const canvas = document.getElementById("sequence-canvas");
const context = canvas.getContext("2d");

// Configuration for the Image Sequence
const config = {
  frameCount: 150, // Total number of frames generated by Google Whisk/Flow
  urlPrefix: "/frames/frame_", // Assumes frames are named frame_000.webp, frame_001.webp, etc.
  urlSuffix: ".webp", // Or .jpg / .png depending on user's export
  padLength: 3 // e.g. 000, 001
};

const images = [];
const imageObj = { frame: 0 };
let imagesLoaded = 0;
let fallbackMode = false;

// Format number with leading zeros
const currentFrame = index => (
  `${config.urlPrefix}${index.toString().padStart(config.padLength, '0')}${config.urlSuffix}`
);

// 1. Resize Handler (Object-fit Cover logic for Canvas)
function resizeCanvas() {
  canvas.width = window.innerWidth;
  canvas.height = window.innerHeight;
  render(); // Re-render current frame on resize
}
window.addEventListener("resize", resizeCanvas);

// 2. Render Loop
function render() {
  if (fallbackMode) {
    renderFallback();
    return;
  }
  
  const img = images[imageObj.frame];
  if (img && img.complete) {
    // Calculate Object-Fit: Cover math
    const hRatio = canvas.width / img.width;
    const vRatio = canvas.height / img.height;
    const ratio = Math.max(hRatio, vRatio);
    const centerShift_x = (canvas.width - img.width * ratio) / 2;
    const centerShift_y = (canvas.height - img.height * ratio) / 2;
    
    context.clearRect(0, 0, canvas.width, canvas.height);
    context.drawImage(
      img, 
      0, 0, img.width, img.height,
      centerShift_x, centerShift_y, img.width * ratio, img.height * ratio
    );
  }
}

// Fallback renderer if frames aren't generated yet
function renderFallback() {
  context.clearRect(0, 0, canvas.width, canvas.height);
  
  // Draw a subtle animated placeholder
  context.fillStyle = "rgba(45, 30, 15, 0.05)"; // subtle dark dots
  
  const progress = imageObj.frame / (config.frameCount - 1); // 0 to 1
  
  // Simulate a scattering effect for the placeholder
  const centerX = canvas.width / 2;
  const centerY = canvas.height / 2;
  const radius = Math.min(canvas.width, canvas.height) * 0.3;
  
  context.beginPath();
  context.arc(centerX, centerY, radius + (progress * 200), 0, Math.PI * 2);
  context.strokeStyle = "rgba(45, 30, 15, 0.1)";
  context.lineWidth = 2;
  context.stroke();
  
  context.fillStyle = "rgba(45, 30, 15, 0.5)";
  context.font = "24px Inter";
  context.textAlign = "center";
  context.fillText("Image Sequence Missing", centerX, centerY - 20);
  context.font = "16px Inter";
  context.fillStyle = "rgba(45, 30, 15, 0.4)";
  context.fillText(`(Frame ${Math.round(imageObj.frame)} / ${config.frameCount})`, centerX, centerY + 20);
  context.fillText("Generate assets using Google Whisk prompts from walkthrough.md", centerX, centerY + 50);
}


// 3. Preload Images
function preloadImages() {
  const loadingOverlay = document.getElementById("loading-overlay");
  const loadProgress = document.getElementById("load-progress");
  
  for (let i = 0; i < config.frameCount; i++) {
    const img = new Image();
    img.src = currentFrame(i);
    
    img.onload = () => {
      imagesLoaded++;
      const percent = Math.round((imagesLoaded / config.frameCount) * 100);
      loadProgress.innerText = `${percent}%`;
      
      // If we loaded the first frame, do an initial render
      if (i === 0) render();
      
      // Hide loader once we have enough frames to start (e.g. 20%)
      if (imagesLoaded > config.frameCount * 0.2 && loadingOverlay.style.opacity !== "0") {
        loadingOverlay.style.opacity = "0";
        setTimeout(() => loadingOverlay.style.display = "none", 800);
      }
    };
    
    img.onerror = () => {
      // If first image fails, assume sequence isn't generated yet and enter fallback mode
      if (i === 0) {
        console.warn("Could not load image sequence. Entering fallback mode.");
        fallbackMode = true;
        loadingOverlay.style.opacity = "0";
        setTimeout(() => loadingOverlay.style.display = "none", 800);
        render();
      }
    };
    
    images.push(img);
  }
}

// 4. Setup Scroll Animations
function setupAnimations() {
  // A. Scrub the image sequence based on total scroll height
  gsap.to(imageObj, {
    frame: config.frameCount - 1,
    snap: "frame",
    ease: "none",
    scrollTrigger: {
      scrub: 0.5,
      trigger: "main",
      start: "top top",
      end: "bottom bottom"
    },
    onUpdate: render
  });

  // B. Fade in and translate the content blocks with cinematic precision
  const blocks = gsap.utils.toArray('.content-block');
  
  // Set initial state for GSAP (in addition to CSS)
  gsap.set(blocks, { y: 60, autoAlpha: 0 });
  
  blocks.forEach(block => {
    gsap.to(block, {
      y: 0,
      autoAlpha: 1,
      duration: 1.2,
      ease: "power3.out",
      scrollTrigger: {
        trigger: block,
        start: "top 80%", 
        end: "bottom 20%",
        toggleActions: "play reverse play reverse", 
      }
    });
  });
}

// 5. Initialize
resizeCanvas();
preloadImages();
setupAnimations();
